# Site settings
title: Fedora Silverblue
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jimmac.github.io/silverblue.fedoraproject.org" # the base hostname & protocol for your site
sourceurl: "https://github.com/jimmac/silverblue.fedoraproject.org"
description: "Immutable Fedora Operating System"
issuesurl: "https://github.com/jimmac/silverblue.fedoraproject.org/issues"
permalink: /:title/

# Build settings
markdown: kramdown
